// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_user.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM admin_users
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR LOWER(username) LIKE '%' || LOWER($1::text) || '%')
  AND ($2::smallint IS NULL OR role = $2)
  AND ($3::smallint IS NULL OR status = $3)
`

type CountAdminsParams struct {
	FilterUsername pgtype.Text `json:"filter_username"`
	FilterRole     pgtype.Int2 `json:"filter_role"`
	FilterStatus   pgtype.Int2 `json:"filter_status"`
}

func (q *Queries) CountAdmins(ctx context.Context, arg CountAdminsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins, arg.FilterUsername, arg.FilterRole, arg.FilterStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin_users (username, password_hash, role, full_name, phone, avatar_url, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, password_hash, role, full_name, phone, avatar_url, status, last_login_at, created_at, updated_at, deleted_at
`

type CreateAdminParams struct {
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Role         int16       `json:"role"`
	FullName     pgtype.Text `json:"full_name"`
	Phone        pgtype.Text `json:"phone"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	Status       int16       `json:"status"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.FullName,
		arg.Phone,
		arg.AvatarUrl,
		arg.Status,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, username, password_hash, role, full_name, phone, avatar_url, status, last_login_at, created_at, updated_at, deleted_at FROM admin_users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAdminByID(ctx context.Context, id int64) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, role, full_name, phone, avatar_url, status, last_login_at, created_at, updated_at, deleted_at FROM admin_users
WHERE LOWER(username) = LOWER($1) AND deleted_at IS NULL
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, username, role, full_name, phone, avatar_url, status,
       last_login_at, created_at
FROM admin_users
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR LOWER(username) LIKE '%' || LOWER($1::text) || '%')
  AND ($2::smallint IS NULL OR role = $2)
  AND ($3::smallint IS NULL OR status = $3)
ORDER BY id ASC
OFFSET $4 LIMIT $5
`

type ListAdminsParams struct {
	FilterUsername pgtype.Text `json:"filter_username"`
	FilterRole     pgtype.Int2 `json:"filter_role"`
	FilterStatus   pgtype.Int2 `json:"filter_status"`
	OffsetVal      int32       `json:"offset_val"`
	LimitVal       int32       `json:"limit_val"`
}

type ListAdminsRow struct {
	ID          int64       `json:"id"`
	Username    string      `json:"username"`
	Role        int16       `json:"role"`
	FullName    pgtype.Text `json:"full_name"`
	Phone       pgtype.Text `json:"phone"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Status      int16       `json:"status"`
	LastLoginAt *time.Time  `json:"last_login_at"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) ListAdmins(ctx context.Context, arg ListAdminsParams) ([]ListAdminsRow, error) {
	rows, err := q.db.Query(ctx, listAdmins,
		arg.FilterUsername,
		arg.FilterRole,
		arg.FilterStatus,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminsRow{}
	for rows.Next() {
		var i ListAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.FullName,
			&i.Phone,
			&i.AvatarUrl,
			&i.Status,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAdmin = `-- name: SoftDeleteAdmin :exec
UPDATE admin_users
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAdmin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteAdmin, id)
	return err
}

const updateAdmin = `-- name: UpdateAdmin :one
UPDATE admin_users
SET full_name = COALESCE(NULLIF($1, ''), full_name),
    phone = COALESCE(NULLIF($2, ''), phone),
    avatar_url = COALESCE(NULLIF($3, ''), avatar_url),
    role = CASE WHEN $4::boolean THEN $5 ELSE role END,
    status = CASE WHEN $6::boolean THEN $7 ELSE status END,
    updated_at = NOW()
WHERE id = $8 AND deleted_at IS NULL
RETURNING id, username, password_hash, role, full_name, phone, avatar_url, status, last_login_at, created_at, updated_at, deleted_at
`

type UpdateAdminParams struct {
	FullName  interface{} `json:"full_name"`
	Phone     interface{} `json:"phone"`
	AvatarUrl interface{} `json:"avatar_url"`
	SetRole   bool        `json:"set_role"`
	Role      int16       `json:"role"`
	SetStatus bool        `json:"set_status"`
	Status    int16       `json:"status"`
	ID        int64       `json:"id"`
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, updateAdmin,
		arg.FullName,
		arg.Phone,
		arg.AvatarUrl,
		arg.SetRole,
		arg.Role,
		arg.SetStatus,
		arg.Status,
		arg.ID,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAdminLastLogin = `-- name: UpdateAdminLastLogin :exec
UPDATE admin_users SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAdminLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateAdminLastLogin, id)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admin_users
SET password_hash = $1, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateAdminPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.PasswordHash, arg.ID)
	return err
}
