// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDiamonds = `-- name: AddDiamonds :exec
UPDATE customers SET diamond_balance = diamond_balance + $1, updated_at = NOW()
WHERE id = $2
`

type AddDiamondsParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddDiamonds(ctx context.Context, arg AddDiamondsParams) error {
	_, err := q.db.Exec(ctx, addDiamonds, arg.Amount, arg.ID)
	return err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (username, password_hash, name)
VALUES ($1, $2, $1)
RETURNING id, username, password_hash, name, phone, email, avatar_url, signature, is_vip, diamond_balance, withdrawal_password_hash, last_login_at, created_at, updated_at, deleted_at
`

type CreateCustomerParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.Username, arg.PasswordHash)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AvatarUrl,
		&i.Signature,
		&i.IsVip,
		&i.DiamondBalance,
		&i.WithdrawalPasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, username, password_hash, name, phone, email, avatar_url, signature, is_vip, diamond_balance, withdrawal_password_hash, last_login_at, created_at, updated_at, deleted_at FROM customers
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomerByID(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AvatarUrl,
		&i.Signature,
		&i.IsVip,
		&i.DiamondBalance,
		&i.WithdrawalPasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerByUsername = `-- name: GetCustomerByUsername :one
SELECT id, username, password_hash, name, phone, email, avatar_url, signature, is_vip, diamond_balance, withdrawal_password_hash, last_login_at, created_at, updated_at, deleted_at FROM customers
WHERE LOWER(username) = LOWER($1) AND deleted_at IS NULL
`

func (q *Queries) GetCustomerByUsername(ctx context.Context, username string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByUsername, username)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AvatarUrl,
		&i.Signature,
		&i.IsVip,
		&i.DiamondBalance,
		&i.WithdrawalPasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerProfile = `-- name: GetCustomerProfile :one
SELECT id, username, name, phone, email, avatar_url, signature,
       is_vip, diamond_balance, last_login_at, created_at
FROM customers WHERE id = $1 AND deleted_at IS NULL
`

type GetCustomerProfileRow struct {
	ID             int64       `json:"id"`
	Username       string      `json:"username"`
	Name           pgtype.Text `json:"name"`
	Phone          pgtype.Text `json:"phone"`
	Email          pgtype.Text `json:"email"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	Signature      pgtype.Text `json:"signature"`
	IsVip          bool        `json:"is_vip"`
	DiamondBalance int64       `json:"diamond_balance"`
	LastLoginAt    *time.Time  `json:"last_login_at"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) GetCustomerProfile(ctx context.Context, id int64) (GetCustomerProfileRow, error) {
	row := q.db.QueryRow(ctx, getCustomerProfile, id)
	var i GetCustomerProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AvatarUrl,
		&i.Signature,
		&i.IsVip,
		&i.DiamondBalance,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateCustomerLastLogin = `-- name: UpdateCustomerLastLogin :exec
UPDATE customers SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateCustomerLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateCustomerLastLogin, id)
	return err
}

const updateCustomerPassword = `-- name: UpdateCustomerPassword :exec
UPDATE customers SET password_hash = $1, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateCustomerPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateCustomerPassword(ctx context.Context, arg UpdateCustomerPasswordParams) error {
	_, err := q.db.Exec(ctx, updateCustomerPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateCustomerProfile = `-- name: UpdateCustomerProfile :one
UPDATE customers SET
    name = COALESCE(NULLIF($1, ''), name),
    phone = COALESCE(NULLIF($2, ''), phone),
    email = COALESCE(NULLIF($3, ''), email),
    avatar_url = COALESCE(NULLIF($4, ''), avatar_url),
    signature = COALESCE(NULLIF($5, ''), signature),
    updated_at = NOW()
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, username, password_hash, name, phone, email, avatar_url, signature, is_vip, diamond_balance, withdrawal_password_hash, last_login_at, created_at, updated_at, deleted_at
`

type UpdateCustomerProfileParams struct {
	Name      interface{} `json:"name"`
	Phone     interface{} `json:"phone"`
	Email     interface{} `json:"email"`
	AvatarUrl interface{} `json:"avatar_url"`
	Signature interface{} `json:"signature"`
	ID        int64       `json:"id"`
}

func (q *Queries) UpdateCustomerProfile(ctx context.Context, arg UpdateCustomerProfileParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerProfile,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.AvatarUrl,
		arg.Signature,
		arg.ID,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AvatarUrl,
		&i.Signature,
		&i.IsVip,
		&i.DiamondBalance,
		&i.WithdrawalPasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
