// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_admin.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*) FROM customers
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR LOWER(name) LIKE '%' || LOWER($1::text) || '%')
  AND ($2::boolean IS NULL OR is_vip = $2)
`

type CountCustomersParams struct {
	FilterName  pgtype.Text `json:"filter_name"`
	FilterIsVip pgtype.Bool `json:"filter_is_vip"`
}

func (q *Queries) CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers, arg.FilterName, arg.FilterIsVip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, username, name, phone, email, avatar_url, signature,
       is_vip, diamond_balance, last_login_at, created_at
FROM customers
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR LOWER(name) LIKE '%' || LOWER($1::text) || '%')
  AND ($2::boolean IS NULL OR is_vip = $2)
ORDER BY id DESC
OFFSET $3 LIMIT $4
`

type ListCustomersParams struct {
	FilterName  pgtype.Text `json:"filter_name"`
	FilterIsVip pgtype.Bool `json:"filter_is_vip"`
	OffsetVal   int32       `json:"offset_val"`
	LimitVal    int32       `json:"limit_val"`
}

type ListCustomersRow struct {
	ID             int64       `json:"id"`
	Username       string      `json:"username"`
	Name           pgtype.Text `json:"name"`
	Phone          pgtype.Text `json:"phone"`
	Email          pgtype.Text `json:"email"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	Signature      pgtype.Text `json:"signature"`
	IsVip          bool        `json:"is_vip"`
	DiamondBalance int64       `json:"diamond_balance"`
	LastLoginAt    *time.Time  `json:"last_login_at"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.FilterName,
		arg.FilterIsVip,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomersRow{}
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.AvatarUrl,
			&i.Signature,
			&i.IsVip,
			&i.DiamondBalance,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetCustomerPassword = `-- name: ResetCustomerPassword :exec
UPDATE customers
SET password_hash = $1, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type ResetCustomerPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) ResetCustomerPassword(ctx context.Context, arg ResetCustomerPasswordParams) error {
	_, err := q.db.Exec(ctx, resetCustomerPassword, arg.PasswordHash, arg.ID)
	return err
}
