// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUser struct {
	ID           int64       `json:"id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Role         int16       `json:"role"`
	FullName     pgtype.Text `json:"full_name"`
	Phone        pgtype.Text `json:"phone"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	Status       int16       `json:"status"`
	LastLoginAt  *time.Time  `json:"last_login_at"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	DeletedAt    *time.Time  `json:"deleted_at"`
}

type Customer struct {
	ID                     int64       `json:"id"`
	Username               string      `json:"username"`
	PasswordHash           string      `json:"password_hash"`
	Name                   pgtype.Text `json:"name"`
	Phone                  pgtype.Text `json:"phone"`
	Email                  pgtype.Text `json:"email"`
	AvatarUrl              pgtype.Text `json:"avatar_url"`
	Signature              pgtype.Text `json:"signature"`
	IsVip                  bool        `json:"is_vip"`
	DiamondBalance         int64       `json:"diamond_balance"`
	WithdrawalPasswordHash pgtype.Text `json:"withdrawal_password_hash"`
	LastLoginAt            *time.Time  `json:"last_login_at"`
	CreatedAt              time.Time   `json:"created_at"`
	UpdatedAt              time.Time   `json:"updated_at"`
	DeletedAt              *time.Time  `json:"deleted_at"`
}

type CustomerSignInRecord struct {
	ID             int64     `json:"id"`
	CustomerID     int64     `json:"customer_id"`
	PeriodKey      string    `json:"period_key"`
	RewardDiamonds int32     `json:"reward_diamonds"`
	CreatedAt      time.Time `json:"created_at"`
}

type TaskDefinition struct {
	ID             int64       `json:"id"`
	TaskCode       string      `json:"task_code"`
	TaskName       string      `json:"task_name"`
	Description    pgtype.Text `json:"description"`
	TaskType       int16       `json:"task_type"`
	TaskCategory   int16       `json:"task_category"`
	TargetCount    int32       `json:"target_count"`
	RewardDiamonds int32       `json:"reward_diamonds"`
	IconUrl        pgtype.Text `json:"icon_url"`
	DisplayOrder   int32       `json:"display_order"`
	VipOnly        bool        `json:"vip_only"`
	Status         int16       `json:"status"`
	StartTime      *time.Time  `json:"start_time"`
	EndTime        *time.Time  `json:"end_time"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type TaskProgress struct {
	ID             int64      `json:"id"`
	CustomerID     int64      `json:"customer_id"`
	TaskID         int64      `json:"task_id"`
	CurrentCount   int32      `json:"current_count"`
	TargetCount    int32      `json:"target_count"`
	PeriodKey      string     `json:"period_key"`
	TaskStatus     int16      `json:"task_status"`
	RewardDiamonds int32      `json:"reward_diamonds"`
	CompletedAt    *time.Time `json:"completed_at"`
	ClaimedAt      *time.Time `json:"claimed_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type UserFollow struct {
	ID         int64     `json:"id"`
	FollowerID int64     `json:"follower_id"`
	FollowedID int64     `json:"followed_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Video struct {
	ID            int64       `json:"id"`
	CustomerID    int64       `json:"customer_id"`
	Title         pgtype.Text `json:"title"`
	Description   pgtype.Text `json:"description"`
	FileName      string      `json:"file_name"`
	FileSize      int64       `json:"file_size"`
	FileUrl       string      `json:"file_url"`
	ThumbnailUrl  pgtype.Text `json:"thumbnail_url"`
	PreviewGifUrl pgtype.Text `json:"preview_gif_url"`
	MimeType      string      `json:"mime_type"`
	Duration      pgtype.Int4 `json:"duration"`
	Width         pgtype.Int4 `json:"width"`
	Height        pgtype.Int4 `json:"height"`
	Status        int16       `json:"status"`
	ReviewNotes   pgtype.Text `json:"review_notes"`
	ReviewedBy    pgtype.Int8 `json:"reviewed_by"`
	ReviewedAt    *time.Time  `json:"reviewed_at"`
	TotalClicks   int64       `json:"total_clicks"`
	ValidClicks   int64       `json:"valid_clicks"`
	LikeCount     int64       `json:"like_count"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	DeletedAt     *time.Time  `json:"deleted_at"`
}

type VideoLike struct {
	ID         int64     `json:"id"`
	VideoID    int64     `json:"video_id"`
	CustomerID int64     `json:"customer_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type VideoPlayRecord struct {
	ID         int64       `json:"id"`
	VideoID    int64       `json:"video_id"`
	CustomerID pgtype.Int8 `json:"customer_id"`
	PlayType   int16       `json:"play_type"`
	IpAddress  pgtype.Text `json:"ip_address"`
	CreatedAt  time.Time   `json:"created_at"`
}
