// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const reportRevenue = `-- name: ReportRevenue :many
SELECT DATE(tp.claimed_at AT TIME ZONE 'Asia/Shanghai') AS report_date,
       COUNT(*) AS claim_count,
       SUM(tp.reward_diamonds) AS total_diamonds
FROM task_progress tp
WHERE tp.task_status = 3
  AND tp.claimed_at >= $1
  AND tp.claimed_at < $2
GROUP BY report_date
ORDER BY report_date DESC
OFFSET $3 LIMIT $4
`

type ReportRevenueParams struct {
	StartDate *time.Time `json:"start_date"`
	EndDate   *time.Time `json:"end_date"`
	OffsetVal int32      `json:"offset_val"`
	LimitVal  int32      `json:"limit_val"`
}

type ReportRevenueRow struct {
	ReportDate    pgtype.Date `json:"report_date"`
	ClaimCount    int64       `json:"claim_count"`
	TotalDiamonds int64       `json:"total_diamonds"`
}

func (q *Queries) ReportRevenue(ctx context.Context, arg ReportRevenueParams) ([]ReportRevenueRow, error) {
	rows, err := q.db.Query(ctx, reportRevenue,
		arg.StartDate,
		arg.EndDate,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportRevenueRow{}
	for rows.Next() {
		var i ReportRevenueRow
		if err := rows.Scan(&i.ReportDate, &i.ClaimCount, &i.TotalDiamonds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportRevenueTotal = `-- name: ReportRevenueTotal :one
SELECT COUNT(DISTINCT DATE(tp.claimed_at AT TIME ZONE 'Asia/Shanghai')) AS total_days
FROM task_progress tp
WHERE tp.task_status = 3
  AND tp.claimed_at >= $1
  AND tp.claimed_at < $2
`

type ReportRevenueTotalParams struct {
	StartDate *time.Time `json:"start_date"`
	EndDate   *time.Time `json:"end_date"`
}

func (q *Queries) ReportRevenueTotal(ctx context.Context, arg ReportRevenueTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, reportRevenueTotal, arg.StartDate, arg.EndDate)
	var total_days int64
	err := row.Scan(&total_days)
	return total_days, err
}

const reportVideoSummary = `-- name: ReportVideoSummary :one
SELECT COUNT(*)::bigint AS total_videos,
       COALESCE(SUM(CASE WHEN status = 4 THEN 1 ELSE 0 END), 0)::bigint AS approved_count,
       COALESCE(SUM(CASE WHEN status = 3 THEN 1 ELSE 0 END), 0)::bigint AS pending_count,
       COALESCE(SUM(CASE WHEN status = 5 THEN 1 ELSE 0 END), 0)::bigint AS rejected_count,
       COALESCE(SUM(total_clicks), 0)::bigint AS total_clicks,
       COALESCE(SUM(valid_clicks), 0)::bigint AS total_valid_clicks,
       COALESCE(SUM(like_count), 0)::bigint AS total_likes
FROM videos
WHERE deleted_at IS NULL
  AND created_at >= $1
  AND created_at < $2
`

type ReportVideoSummaryParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type ReportVideoSummaryRow struct {
	TotalVideos      int64 `json:"total_videos"`
	ApprovedCount    int64 `json:"approved_count"`
	PendingCount     int64 `json:"pending_count"`
	RejectedCount    int64 `json:"rejected_count"`
	TotalClicks      int64 `json:"total_clicks"`
	TotalValidClicks int64 `json:"total_valid_clicks"`
	TotalLikes       int64 `json:"total_likes"`
}

func (q *Queries) ReportVideoSummary(ctx context.Context, arg ReportVideoSummaryParams) (ReportVideoSummaryRow, error) {
	row := q.db.QueryRow(ctx, reportVideoSummary, arg.StartDate, arg.EndDate)
	var i ReportVideoSummaryRow
	err := row.Scan(
		&i.TotalVideos,
		&i.ApprovedCount,
		&i.PendingCount,
		&i.RejectedCount,
		&i.TotalClicks,
		&i.TotalValidClicks,
		&i.TotalLikes,
	)
	return i, err
}

const reportVideosDaily = `-- name: ReportVideosDaily :many
SELECT DATE(v.created_at AT TIME ZONE 'Asia/Shanghai') AS report_date,
       COUNT(*) AS upload_count,
       SUM(v.total_clicks) AS total_clicks,
       SUM(v.valid_clicks) AS total_valid_clicks,
       SUM(v.like_count) AS total_likes
FROM videos v
WHERE v.deleted_at IS NULL
  AND v.created_at >= $1
  AND v.created_at < $2
GROUP BY report_date
ORDER BY report_date DESC
OFFSET $3 LIMIT $4
`

type ReportVideosDailyParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	OffsetVal int32     `json:"offset_val"`
	LimitVal  int32     `json:"limit_val"`
}

type ReportVideosDailyRow struct {
	ReportDate       pgtype.Date `json:"report_date"`
	UploadCount      int64       `json:"upload_count"`
	TotalClicks      int64       `json:"total_clicks"`
	TotalValidClicks int64       `json:"total_valid_clicks"`
	TotalLikes       int64       `json:"total_likes"`
}

func (q *Queries) ReportVideosDaily(ctx context.Context, arg ReportVideosDailyParams) ([]ReportVideosDailyRow, error) {
	rows, err := q.db.Query(ctx, reportVideosDaily,
		arg.StartDate,
		arg.EndDate,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportVideosDailyRow{}
	for rows.Next() {
		var i ReportVideosDailyRow
		if err := rows.Scan(
			&i.ReportDate,
			&i.UploadCount,
			&i.TotalClicks,
			&i.TotalValidClicks,
			&i.TotalLikes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportVideosDailyTotal = `-- name: ReportVideosDailyTotal :one
SELECT COUNT(DISTINCT DATE(v.created_at AT TIME ZONE 'Asia/Shanghai')) AS total_days
FROM videos v
WHERE v.deleted_at IS NULL
  AND v.created_at >= $1
  AND v.created_at < $2
`

type ReportVideosDailyTotalParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) ReportVideosDailyTotal(ctx context.Context, arg ReportVideosDailyTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, reportVideosDailyTotal, arg.StartDate, arg.EndDate)
	var total_days int64
	err := row.Scan(&total_days)
	return total_days, err
}
