// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sign_in.sql

package repository

import (
	"context"
)

const hasSignedInToday = `-- name: HasSignedInToday :one
SELECT EXISTS(
    SELECT 1 FROM customer_sign_in_records
    WHERE customer_id = $1 AND period_key = $2
) AS signed
`

type HasSignedInTodayParams struct {
	CustomerID int64  `json:"customer_id"`
	PeriodKey  string `json:"period_key"`
}

func (q *Queries) HasSignedInToday(ctx context.Context, arg HasSignedInTodayParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSignedInToday, arg.CustomerID, arg.PeriodKey)
	var signed bool
	err := row.Scan(&signed)
	return signed, err
}

const recordSignIn = `-- name: RecordSignIn :one
INSERT INTO customer_sign_in_records (customer_id, period_key, reward_diamonds)
VALUES ($1, $2, $3)
RETURNING id, customer_id, period_key, reward_diamonds, created_at
`

type RecordSignInParams struct {
	CustomerID     int64  `json:"customer_id"`
	PeriodKey      string `json:"period_key"`
	RewardDiamonds int32  `json:"reward_diamonds"`
}

func (q *Queries) RecordSignIn(ctx context.Context, arg RecordSignInParams) (CustomerSignInRecord, error) {
	row := q.db.QueryRow(ctx, recordSignIn, arg.CustomerID, arg.PeriodKey, arg.RewardDiamonds)
	var i CustomerSignInRecord
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.PeriodKey,
		&i.RewardDiamonds,
		&i.CreatedAt,
	)
	return i, err
}
