// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_progress.sql

package repository

import (
	"context"
	"time"
)

const addCustomerDiamonds = `-- name: AddCustomerDiamonds :exec
UPDATE customers
SET diamond_balance = diamond_balance + $1
WHERE id = $2
`

type AddCustomerDiamondsParams struct {
	Amount     int64 `json:"amount"`
	CustomerID int64 `json:"customer_id"`
}

func (q *Queries) AddCustomerDiamonds(ctx context.Context, arg AddCustomerDiamondsParams) error {
	_, err := q.db.Exec(ctx, addCustomerDiamonds, arg.Amount, arg.CustomerID)
	return err
}

const claimTaskProgress = `-- name: ClaimTaskProgress :exec
UPDATE task_progress
SET task_status = 3, claimed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClaimTaskProgress(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, claimTaskProgress, id)
	return err
}

const getTaskProgressByCustomerAndPeriod = `-- name: GetTaskProgressByCustomerAndPeriod :many
SELECT tp.id, tp.customer_id, tp.task_id, tp.current_count, tp.target_count,
       tp.period_key, tp.task_status, tp.reward_diamonds,
       tp.completed_at, tp.claimed_at, tp.created_at
FROM task_progress tp
WHERE tp.customer_id = $1
  AND tp.period_key = $2
ORDER BY tp.task_id ASC
`

type GetTaskProgressByCustomerAndPeriodParams struct {
	CustomerID int64  `json:"customer_id"`
	PeriodKey  string `json:"period_key"`
}

type GetTaskProgressByCustomerAndPeriodRow struct {
	ID             int64      `json:"id"`
	CustomerID     int64      `json:"customer_id"`
	TaskID         int64      `json:"task_id"`
	CurrentCount   int32      `json:"current_count"`
	TargetCount    int32      `json:"target_count"`
	PeriodKey      string     `json:"period_key"`
	TaskStatus     int16      `json:"task_status"`
	RewardDiamonds int32      `json:"reward_diamonds"`
	CompletedAt    *time.Time `json:"completed_at"`
	ClaimedAt      *time.Time `json:"claimed_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

func (q *Queries) GetTaskProgressByCustomerAndPeriod(ctx context.Context, arg GetTaskProgressByCustomerAndPeriodParams) ([]GetTaskProgressByCustomerAndPeriodRow, error) {
	rows, err := q.db.Query(ctx, getTaskProgressByCustomerAndPeriod, arg.CustomerID, arg.PeriodKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskProgressByCustomerAndPeriodRow{}
	for rows.Next() {
		var i GetTaskProgressByCustomerAndPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.TaskID,
			&i.CurrentCount,
			&i.TargetCount,
			&i.PeriodKey,
			&i.TaskStatus,
			&i.RewardDiamonds,
			&i.CompletedAt,
			&i.ClaimedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskProgressForUpdate = `-- name: GetTaskProgressForUpdate :one
SELECT id, customer_id, task_id, current_count, target_count,
       task_status, reward_diamonds
FROM task_progress
WHERE id = $1 AND customer_id = $2
FOR UPDATE
`

type GetTaskProgressForUpdateParams struct {
	ID         int64 `json:"id"`
	CustomerID int64 `json:"customer_id"`
}

type GetTaskProgressForUpdateRow struct {
	ID             int64 `json:"id"`
	CustomerID     int64 `json:"customer_id"`
	TaskID         int64 `json:"task_id"`
	CurrentCount   int32 `json:"current_count"`
	TargetCount    int32 `json:"target_count"`
	TaskStatus     int16 `json:"task_status"`
	RewardDiamonds int32 `json:"reward_diamonds"`
}

func (q *Queries) GetTaskProgressForUpdate(ctx context.Context, arg GetTaskProgressForUpdateParams) (GetTaskProgressForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTaskProgressForUpdate, arg.ID, arg.CustomerID)
	var i GetTaskProgressForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TaskID,
		&i.CurrentCount,
		&i.TargetCount,
		&i.TaskStatus,
		&i.RewardDiamonds,
	)
	return i, err
}

const getWatchTaskIDs = `-- name: GetWatchTaskIDs :many
SELECT id FROM task_definitions
WHERE status = 1
  AND task_category = 1
  AND (start_time IS NULL OR start_time <= NOW())
  AND (end_time IS NULL OR end_time > NOW())
`

func (q *Queries) GetWatchTaskIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getWatchTaskIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrTaskProgressCount = `-- name: IncrTaskProgressCount :exec
UPDATE task_progress
SET current_count = current_count + 1,
    task_status = CASE
        WHEN current_count + 1 >= target_count THEN 2
        ELSE task_status
    END,
    completed_at = CASE
        WHEN current_count + 1 >= target_count AND completed_at IS NULL THEN NOW()
        ELSE completed_at
    END,
    updated_at = NOW()
WHERE customer_id = $1
  AND task_id = $2
  AND period_key = $3
  AND task_status = 1
`

type IncrTaskProgressCountParams struct {
	CustomerID int64  `json:"customer_id"`
	TaskID     int64  `json:"task_id"`
	PeriodKey  string `json:"period_key"`
}

func (q *Queries) IncrTaskProgressCount(ctx context.Context, arg IncrTaskProgressCountParams) error {
	_, err := q.db.Exec(ctx, incrTaskProgressCount, arg.CustomerID, arg.TaskID, arg.PeriodKey)
	return err
}

const upsertTaskProgress = `-- name: UpsertTaskProgress :one
INSERT INTO task_progress (customer_id, task_id, target_count, period_key, reward_diamonds)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (customer_id, task_id, period_key) DO NOTHING
RETURNING id, customer_id, task_id, current_count, target_count, period_key, task_status, reward_diamonds, completed_at, claimed_at, created_at, updated_at
`

type UpsertTaskProgressParams struct {
	CustomerID     int64  `json:"customer_id"`
	TaskID         int64  `json:"task_id"`
	TargetCount    int32  `json:"target_count"`
	PeriodKey      string `json:"period_key"`
	RewardDiamonds int32  `json:"reward_diamonds"`
}

func (q *Queries) UpsertTaskProgress(ctx context.Context, arg UpsertTaskProgressParams) (TaskProgress, error) {
	row := q.db.QueryRow(ctx, upsertTaskProgress,
		arg.CustomerID,
		arg.TaskID,
		arg.TargetCount,
		arg.PeriodKey,
		arg.RewardDiamonds,
	)
	var i TaskProgress
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TaskID,
		&i.CurrentCount,
		&i.TargetCount,
		&i.PeriodKey,
		&i.TaskStatus,
		&i.RewardDiamonds,
		&i.CompletedAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
