// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_definition.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveTaskDefinitions = `-- name: ListActiveTaskDefinitions :many
SELECT id, task_code, task_name, description, task_type, task_category,
       target_count, reward_diamonds, icon_url, display_order, vip_only
FROM task_definitions
WHERE status = 1
  AND (start_time IS NULL OR start_time <= NOW())
  AND (end_time IS NULL OR end_time > NOW())
ORDER BY display_order ASC, id ASC
`

type ListActiveTaskDefinitionsRow struct {
	ID             int64       `json:"id"`
	TaskCode       string      `json:"task_code"`
	TaskName       string      `json:"task_name"`
	Description    pgtype.Text `json:"description"`
	TaskType       int16       `json:"task_type"`
	TaskCategory   int16       `json:"task_category"`
	TargetCount    int32       `json:"target_count"`
	RewardDiamonds int32       `json:"reward_diamonds"`
	IconUrl        pgtype.Text `json:"icon_url"`
	DisplayOrder   int32       `json:"display_order"`
	VipOnly        bool        `json:"vip_only"`
}

func (q *Queries) ListActiveTaskDefinitions(ctx context.Context) ([]ListActiveTaskDefinitionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTaskDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTaskDefinitionsRow{}
	for rows.Next() {
		var i ListActiveTaskDefinitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskCode,
			&i.TaskName,
			&i.Description,
			&i.TaskType,
			&i.TaskCategory,
			&i.TargetCount,
			&i.RewardDiamonds,
			&i.IconUrl,
			&i.DisplayOrder,
			&i.VipOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
