// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_follow.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*) FROM user_follows uf
JOIN customers c ON c.id = uf.follower_id AND c.deleted_at IS NULL
WHERE uf.followed_id = $1
`

func (q *Queries) CountFollowers(ctx context.Context, followedID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowers, followedID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*) FROM user_follows uf
JOIN customers c ON c.id = uf.followed_id AND c.deleted_at IS NULL
WHERE uf.follower_id = $1
`

func (q *Queries) CountFollowing(ctx context.Context, followerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowing, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO user_follows (follower_id, followed_id)
VALUES ($1, $2)
ON CONFLICT (follower_id, followed_id) DO NOTHING
`

type FollowUserParams struct {
	FollowerID int64 `json:"follower_id"`
	FollowedID int64 `json:"followed_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FollowedID)
	return err
}

const getFollowersList = `-- name: GetFollowersList :many
SELECT uf.follower_id AS user_id,
       c.username,
       c.name,
       c.avatar_url,
       CASE WHEN $1::bigint IS NOT NULL THEN
           EXISTS(SELECT 1 FROM user_follows WHERE follower_id = $1 AND followed_id = uf.follower_id)
       ELSE false END AS viewer_is_following,
       CASE WHEN $1::bigint IS NOT NULL THEN
           EXISTS(SELECT 1 FROM user_follows WHERE follower_id = uf.follower_id AND followed_id = $1)
       ELSE false END AS viewer_is_followed_by
FROM user_follows uf
JOIN customers c ON c.id = uf.follower_id AND c.deleted_at IS NULL
WHERE uf.followed_id = $2
ORDER BY uf.created_at DESC
LIMIT $4 OFFSET $3
`

type GetFollowersListParams struct {
	ViewerID   pgtype.Int8 `json:"viewer_id"`
	FollowedID int64       `json:"followed_id"`
	OffsetVal  int32       `json:"offset_val"`
	LimitVal   int32       `json:"limit_val"`
}

type GetFollowersListRow struct {
	UserID             int64       `json:"user_id"`
	Username           string      `json:"username"`
	Name               pgtype.Text `json:"name"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
	ViewerIsFollowing  bool        `json:"viewer_is_following"`
	ViewerIsFollowedBy bool        `json:"viewer_is_followed_by"`
}

func (q *Queries) GetFollowersList(ctx context.Context, arg GetFollowersListParams) ([]GetFollowersListRow, error) {
	rows, err := q.db.Query(ctx, getFollowersList,
		arg.ViewerID,
		arg.FollowedID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowersListRow{}
	for rows.Next() {
		var i GetFollowersListRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.ViewerIsFollowing,
			&i.ViewerIsFollowedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingList = `-- name: GetFollowingList :many
SELECT uf.followed_id AS user_id,
       c.username,
       c.name,
       c.avatar_url,
       CASE WHEN $1::bigint IS NOT NULL THEN
           EXISTS(SELECT 1 FROM user_follows WHERE follower_id = $1 AND followed_id = uf.followed_id)
       ELSE false END AS viewer_is_following,
       CASE WHEN $1::bigint IS NOT NULL THEN
           EXISTS(SELECT 1 FROM user_follows WHERE follower_id = uf.followed_id AND followed_id = $1)
       ELSE false END AS viewer_is_followed_by
FROM user_follows uf
JOIN customers c ON c.id = uf.followed_id AND c.deleted_at IS NULL
WHERE uf.follower_id = $2
ORDER BY uf.created_at DESC
LIMIT $4 OFFSET $3
`

type GetFollowingListParams struct {
	ViewerID   pgtype.Int8 `json:"viewer_id"`
	FollowerID int64       `json:"follower_id"`
	OffsetVal  int32       `json:"offset_val"`
	LimitVal   int32       `json:"limit_val"`
}

type GetFollowingListRow struct {
	UserID             int64       `json:"user_id"`
	Username           string      `json:"username"`
	Name               pgtype.Text `json:"name"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
	ViewerIsFollowing  bool        `json:"viewer_is_following"`
	ViewerIsFollowedBy bool        `json:"viewer_is_followed_by"`
}

func (q *Queries) GetFollowingList(ctx context.Context, arg GetFollowingListParams) ([]GetFollowingListRow, error) {
	rows, err := q.db.Query(ctx, getFollowingList,
		arg.ViewerID,
		arg.FollowerID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowingListRow{}
	for rows.Next() {
		var i GetFollowingListRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.ViewerIsFollowing,
			&i.ViewerIsFollowedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
    SELECT 1 FROM user_follows
    WHERE follower_id = $1 AND followed_id = $2
) AS is_following
`

type IsFollowingParams struct {
	FollowerID int64 `json:"follower_id"`
	FollowedID int64 `json:"followed_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FollowedID)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM user_follows
WHERE follower_id = $1 AND followed_id = $2
`

type UnfollowUserParams struct {
	FollowerID int64 `json:"follower_id"`
	FollowedID int64 `json:"followed_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FollowedID)
	return err
}
