// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_like.sql

package repository

import (
	"context"
)

const isVideoLiked = `-- name: IsVideoLiked :one
SELECT EXISTS(
    SELECT 1 FROM video_likes
    WHERE video_id = $1 AND customer_id = $2
) AS is_liked
`

type IsVideoLikedParams struct {
	VideoID    int64 `json:"video_id"`
	CustomerID int64 `json:"customer_id"`
}

func (q *Queries) IsVideoLiked(ctx context.Context, arg IsVideoLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isVideoLiked, arg.VideoID, arg.CustomerID)
	var is_liked bool
	err := row.Scan(&is_liked)
	return is_liked, err
}

const likeVideo = `-- name: LikeVideo :exec
WITH inserted AS (
    INSERT INTO video_likes (video_id, customer_id)
    VALUES ($1, $2)
    ON CONFLICT (video_id, customer_id) DO NOTHING
    RETURNING video_likes.id
)
UPDATE videos SET like_count = like_count + 1, updated_at = NOW()
WHERE videos.id = $1 AND EXISTS (SELECT 1 FROM inserted)
`

type LikeVideoParams struct {
	VideoID    int64 `json:"video_id"`
	CustomerID int64 `json:"customer_id"`
}

func (q *Queries) LikeVideo(ctx context.Context, arg LikeVideoParams) error {
	_, err := q.db.Exec(ctx, likeVideo, arg.VideoID, arg.CustomerID)
	return err
}

const unlikeVideo = `-- name: UnlikeVideo :exec
WITH deleted AS (
    DELETE FROM video_likes
    WHERE video_likes.video_id = $1 AND video_likes.customer_id = $2
    RETURNING video_likes.id
)
UPDATE videos SET like_count = GREATEST(like_count - 1, 0), updated_at = NOW()
WHERE videos.id = $1 AND EXISTS (SELECT 1 FROM deleted)
`

type UnlikeVideoParams struct {
	VideoID    int64 `json:"video_id"`
	CustomerID int64 `json:"customer_id"`
}

func (q *Queries) UnlikeVideo(ctx context.Context, arg UnlikeVideoParams) error {
	_, err := q.db.Exec(ctx, unlikeVideo, arg.VideoID, arg.CustomerID)
	return err
}
