// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_admin.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountVideos = `-- name: AdminCountVideos :one
SELECT COUNT(*)
FROM videos v
JOIN customers c ON c.id = v.customer_id
WHERE v.deleted_at IS NULL
  AND ($1::text IS NULL OR LOWER(c.username) LIKE '%' || LOWER($1::text) || '%')
  AND ($2::smallint IS NULL OR v.status = $2)
  AND ($3::boolean IS NULL OR c.is_vip = $3)
  AND ($4::timestamptz IS NULL OR v.created_at >= $4)
  AND ($5::timestamptz IS NULL OR v.created_at < $5)
`

type AdminCountVideosParams struct {
	AuthorNameFilter pgtype.Text `json:"author_name_filter"`
	StatusFilter     pgtype.Int2 `json:"status_filter"`
	IsVipFilter      pgtype.Bool `json:"is_vip_filter"`
	StartDate        *time.Time  `json:"start_date"`
	EndDate          *time.Time  `json:"end_date"`
}

func (q *Queries) AdminCountVideos(ctx context.Context, arg AdminCountVideosParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountVideos,
		arg.AuthorNameFilter,
		arg.StatusFilter,
		arg.IsVipFilter,
		arg.StartDate,
		arg.EndDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminDeleteVideo = `-- name: AdminDeleteVideo :exec
UPDATE videos
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) AdminDeleteVideo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, adminDeleteVideo, id)
	return err
}

const adminGetVideoDetail = `-- name: AdminGetVideoDetail :one
SELECT v.id, v.customer_id, v.title, v.description, v.file_name, v.file_size, v.file_url, v.thumbnail_url, v.preview_gif_url, v.mime_type, v.duration, v.width, v.height, v.status, v.review_notes, v.reviewed_by, v.reviewed_at, v.total_clicks, v.valid_clicks, v.like_count, v.created_at, v.updated_at, v.deleted_at, c.username AS author_name, c.avatar_url AS author_avatar
FROM videos v
JOIN customers c ON c.id = v.customer_id
WHERE v.id = $1 AND v.deleted_at IS NULL
`

type AdminGetVideoDetailRow struct {
	ID            int64       `json:"id"`
	CustomerID    int64       `json:"customer_id"`
	Title         pgtype.Text `json:"title"`
	Description   pgtype.Text `json:"description"`
	FileName      string      `json:"file_name"`
	FileSize      int64       `json:"file_size"`
	FileUrl       string      `json:"file_url"`
	ThumbnailUrl  pgtype.Text `json:"thumbnail_url"`
	PreviewGifUrl pgtype.Text `json:"preview_gif_url"`
	MimeType      string      `json:"mime_type"`
	Duration      pgtype.Int4 `json:"duration"`
	Width         pgtype.Int4 `json:"width"`
	Height        pgtype.Int4 `json:"height"`
	Status        int16       `json:"status"`
	ReviewNotes   pgtype.Text `json:"review_notes"`
	ReviewedBy    pgtype.Int8 `json:"reviewed_by"`
	ReviewedAt    *time.Time  `json:"reviewed_at"`
	TotalClicks   int64       `json:"total_clicks"`
	ValidClicks   int64       `json:"valid_clicks"`
	LikeCount     int64       `json:"like_count"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	DeletedAt     *time.Time  `json:"deleted_at"`
	AuthorName    string      `json:"author_name"`
	AuthorAvatar  pgtype.Text `json:"author_avatar"`
}

func (q *Queries) AdminGetVideoDetail(ctx context.Context, id int64) (AdminGetVideoDetailRow, error) {
	row := q.db.QueryRow(ctx, adminGetVideoDetail, id)
	var i AdminGetVideoDetailRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Title,
		&i.Description,
		&i.FileName,
		&i.FileSize,
		&i.FileUrl,
		&i.ThumbnailUrl,
		&i.PreviewGifUrl,
		&i.MimeType,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.TotalClicks,
		&i.ValidClicks,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AuthorName,
		&i.AuthorAvatar,
	)
	return i, err
}

const adminListVideos = `-- name: AdminListVideos :many
SELECT v.id, v.customer_id, v.title, v.file_url, v.thumbnail_url,
       v.mime_type, v.status, v.total_clicks, v.valid_clicks, v.like_count,
       v.created_at, c.username AS author_name
FROM videos v
JOIN customers c ON c.id = v.customer_id
WHERE v.deleted_at IS NULL
  AND ($1::text IS NULL OR LOWER(c.username) LIKE '%' || LOWER($1::text) || '%')
  AND ($2::smallint IS NULL OR v.status = $2)
  AND ($3::boolean IS NULL OR c.is_vip = $3)
  AND ($4::timestamptz IS NULL OR v.created_at >= $4)
  AND ($5::timestamptz IS NULL OR v.created_at < $5)
ORDER BY v.id DESC
OFFSET $6 LIMIT $7
`

type AdminListVideosParams struct {
	AuthorNameFilter pgtype.Text `json:"author_name_filter"`
	StatusFilter     pgtype.Int2 `json:"status_filter"`
	IsVipFilter      pgtype.Bool `json:"is_vip_filter"`
	StartDate        *time.Time  `json:"start_date"`
	EndDate          *time.Time  `json:"end_date"`
	OffsetVal        int32       `json:"offset_val"`
	LimitVal         int32       `json:"limit_val"`
}

type AdminListVideosRow struct {
	ID           int64       `json:"id"`
	CustomerID   int64       `json:"customer_id"`
	Title        pgtype.Text `json:"title"`
	FileUrl      string      `json:"file_url"`
	ThumbnailUrl pgtype.Text `json:"thumbnail_url"`
	MimeType     string      `json:"mime_type"`
	Status       int16       `json:"status"`
	TotalClicks  int64       `json:"total_clicks"`
	ValidClicks  int64       `json:"valid_clicks"`
	LikeCount    int64       `json:"like_count"`
	CreatedAt    time.Time   `json:"created_at"`
	AuthorName   string      `json:"author_name"`
}

func (q *Queries) AdminListVideos(ctx context.Context, arg AdminListVideosParams) ([]AdminListVideosRow, error) {
	rows, err := q.db.Query(ctx, adminListVideos,
		arg.AuthorNameFilter,
		arg.StatusFilter,
		arg.IsVipFilter,
		arg.StartDate,
		arg.EndDate,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListVideosRow{}
	for rows.Next() {
		var i AdminListVideosRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Title,
			&i.FileUrl,
			&i.ThumbnailUrl,
			&i.MimeType,
			&i.Status,
			&i.TotalClicks,
			&i.ValidClicks,
			&i.LikeCount,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewVideo = `-- name: ReviewVideo :exec
UPDATE videos
SET status = $1,
    review_notes = $2,
    reviewed_by = $3,
    reviewed_at = NOW(),
    updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
`

type ReviewVideoParams struct {
	Status      int16       `json:"status"`
	ReviewNotes pgtype.Text `json:"review_notes"`
	ReviewedBy  pgtype.Int8 `json:"reviewed_by"`
	ID          int64       `json:"id"`
}

func (q *Queries) ReviewVideo(ctx context.Context, arg ReviewVideoParams) error {
	_, err := q.db.Exec(ctx, reviewVideo,
		arg.Status,
		arg.ReviewNotes,
		arg.ReviewedBy,
		arg.ID,
	)
	return err
}
