// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMyVideos = `-- name: CountMyVideos :one
SELECT COUNT(*) FROM videos
WHERE customer_id = $1 AND deleted_at IS NULL
  AND ($2::smallint IS NULL OR status = $2)
`

type CountMyVideosParams struct {
	CustomerID int64       `json:"customer_id"`
	Status     pgtype.Int2 `json:"status"`
}

func (q *Queries) CountMyVideos(ctx context.Context, arg CountMyVideosParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMyVideos, arg.CustomerID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVideos = `-- name: CountVideos :one
SELECT COUNT(*) FROM videos
WHERE status = 4 AND deleted_at IS NULL
  AND ($1::text IS NULL OR title ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountVideos(ctx context.Context, keyword pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countVideos, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVideosByCustomer = `-- name: CountVideosByCustomer :one
SELECT COUNT(*) FROM videos
WHERE customer_id = $1 AND status = 4 AND deleted_at IS NULL
`

func (q *Queries) CountVideosByCustomer(ctx context.Context, customerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countVideosByCustomer, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (customer_id, title, description, file_name, file_size, file_url,
                    thumbnail_url, mime_type, duration, width, height, status)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11, $12)
RETURNING id, customer_id, title, description, file_name, file_size, file_url, thumbnail_url, preview_gif_url, mime_type, duration, width, height, status, review_notes, reviewed_by, reviewed_at, total_clicks, valid_clicks, like_count, created_at, updated_at, deleted_at
`

type CreateVideoParams struct {
	CustomerID   int64       `json:"customer_id"`
	Title        pgtype.Text `json:"title"`
	Description  pgtype.Text `json:"description"`
	FileName     string      `json:"file_name"`
	FileSize     int64       `json:"file_size"`
	FileUrl      string      `json:"file_url"`
	ThumbnailUrl pgtype.Text `json:"thumbnail_url"`
	MimeType     string      `json:"mime_type"`
	Duration     pgtype.Int4 `json:"duration"`
	Width        pgtype.Int4 `json:"width"`
	Height       pgtype.Int4 `json:"height"`
	Status       int16       `json:"status"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.CustomerID,
		arg.Title,
		arg.Description,
		arg.FileName,
		arg.FileSize,
		arg.FileUrl,
		arg.ThumbnailUrl,
		arg.MimeType,
		arg.Duration,
		arg.Width,
		arg.Height,
		arg.Status,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Title,
		&i.Description,
		&i.FileName,
		&i.FileSize,
		&i.FileUrl,
		&i.ThumbnailUrl,
		&i.PreviewGifUrl,
		&i.MimeType,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.TotalClicks,
		&i.ValidClicks,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, customer_id, title, description, file_name, file_size, file_url, thumbnail_url, preview_gif_url, mime_type, duration, width, height, status, review_notes, reviewed_by, reviewed_at, total_clicks, valid_clicks, like_count, created_at, updated_at, deleted_at FROM videos
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVideoByID(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Title,
		&i.Description,
		&i.FileName,
		&i.FileSize,
		&i.FileUrl,
		&i.ThumbnailUrl,
		&i.PreviewGifUrl,
		&i.MimeType,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.TotalClicks,
		&i.ValidClicks,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrVideoClicks = `-- name: IncrVideoClicks :exec
UPDATE videos SET total_clicks = total_clicks + 1 WHERE id = $1
`

func (q *Queries) IncrVideoClicks(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrVideoClicks, id)
	return err
}

const incrVideoValidClicks = `-- name: IncrVideoValidClicks :exec
UPDATE videos SET valid_clicks = valid_clicks + 1 WHERE id = $1
`

func (q *Queries) IncrVideoValidClicks(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrVideoValidClicks, id)
	return err
}

const listFeaturedVideos = `-- name: ListFeaturedVideos :many
SELECT v.id, v.customer_id, v.title, v.description, v.file_name, v.file_size, v.file_url, v.thumbnail_url, v.preview_gif_url, v.mime_type, v.duration, v.width, v.height, v.status, v.review_notes, v.reviewed_by, v.reviewed_at, v.total_clicks, v.valid_clicks, v.like_count, v.created_at, v.updated_at, v.deleted_at, c.username AS author_name, c.avatar_url AS author_avatar
FROM videos v
JOIN customers c ON c.id = v.customer_id AND c.deleted_at IS NULL
WHERE v.status = 4 AND v.deleted_at IS NULL
  AND ($1::text IS NULL OR v.title ILIKE '%' || $1::text || '%')
ORDER BY v.like_count DESC, v.created_at DESC
LIMIT $3 OFFSET $2
`

type ListFeaturedVideosParams struct {
	Keyword   pgtype.Text `json:"keyword"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

type ListFeaturedVideosRow struct {
	ID            int64       `json:"id"`
	CustomerID    int64       `json:"customer_id"`
	Title         pgtype.Text `json:"title"`
	Description   pgtype.Text `json:"description"`
	FileName      string      `json:"file_name"`
	FileSize      int64       `json:"file_size"`
	FileUrl       string      `json:"file_url"`
	ThumbnailUrl  pgtype.Text `json:"thumbnail_url"`
	PreviewGifUrl pgtype.Text `json:"preview_gif_url"`
	MimeType      string      `json:"mime_type"`
	Duration      pgtype.Int4 `json:"duration"`
	Width         pgtype.Int4 `json:"width"`
	Height        pgtype.Int4 `json:"height"`
	Status        int16       `json:"status"`
	ReviewNotes   pgtype.Text `json:"review_notes"`
	ReviewedBy    pgtype.Int8 `json:"reviewed_by"`
	ReviewedAt    *time.Time  `json:"reviewed_at"`
	TotalClicks   int64       `json:"total_clicks"`
	ValidClicks   int64       `json:"valid_clicks"`
	LikeCount     int64       `json:"like_count"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	DeletedAt     *time.Time  `json:"deleted_at"`
	AuthorName    string      `json:"author_name"`
	AuthorAvatar  pgtype.Text `json:"author_avatar"`
}

func (q *Queries) ListFeaturedVideos(ctx context.Context, arg ListFeaturedVideosParams) ([]ListFeaturedVideosRow, error) {
	rows, err := q.db.Query(ctx, listFeaturedVideos, arg.Keyword, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeaturedVideosRow{}
	for rows.Next() {
		var i ListFeaturedVideosRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Title,
			&i.Description,
			&i.FileName,
			&i.FileSize,
			&i.FileUrl,
			&i.ThumbnailUrl,
			&i.PreviewGifUrl,
			&i.MimeType,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.Status,
			&i.ReviewNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.TotalClicks,
			&i.ValidClicks,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyVideos = `-- name: ListMyVideos :many
SELECT id, customer_id, title, description, file_name, file_size, file_url, thumbnail_url, preview_gif_url, mime_type, duration, width, height, status, review_notes, reviewed_by, reviewed_at, total_clicks, valid_clicks, like_count, created_at, updated_at, deleted_at FROM videos
WHERE customer_id = $1 AND deleted_at IS NULL
  AND ($2::smallint IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListMyVideosParams struct {
	CustomerID int64       `json:"customer_id"`
	Status     pgtype.Int2 `json:"status"`
	OffsetVal  int32       `json:"offset_val"`
	LimitVal   int32       `json:"limit_val"`
}

func (q *Queries) ListMyVideos(ctx context.Context, arg ListMyVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listMyVideos,
		arg.CustomerID,
		arg.Status,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Title,
			&i.Description,
			&i.FileName,
			&i.FileSize,
			&i.FileUrl,
			&i.ThumbnailUrl,
			&i.PreviewGifUrl,
			&i.MimeType,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.Status,
			&i.ReviewNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.TotalClicks,
			&i.ValidClicks,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideos = `-- name: ListVideos :many
SELECT v.id, v.customer_id, v.title, v.description, v.file_name, v.file_size, v.file_url, v.thumbnail_url, v.preview_gif_url, v.mime_type, v.duration, v.width, v.height, v.status, v.review_notes, v.reviewed_by, v.reviewed_at, v.total_clicks, v.valid_clicks, v.like_count, v.created_at, v.updated_at, v.deleted_at, c.username AS author_name, c.avatar_url AS author_avatar
FROM videos v
JOIN customers c ON c.id = v.customer_id AND c.deleted_at IS NULL
WHERE v.status = 4 AND v.deleted_at IS NULL
  AND ($1::text IS NULL OR v.title ILIKE '%' || $1::text || '%')
ORDER BY v.created_at DESC
LIMIT $3 OFFSET $2
`

type ListVideosParams struct {
	Keyword   pgtype.Text `json:"keyword"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

type ListVideosRow struct {
	ID            int64       `json:"id"`
	CustomerID    int64       `json:"customer_id"`
	Title         pgtype.Text `json:"title"`
	Description   pgtype.Text `json:"description"`
	FileName      string      `json:"file_name"`
	FileSize      int64       `json:"file_size"`
	FileUrl       string      `json:"file_url"`
	ThumbnailUrl  pgtype.Text `json:"thumbnail_url"`
	PreviewGifUrl pgtype.Text `json:"preview_gif_url"`
	MimeType      string      `json:"mime_type"`
	Duration      pgtype.Int4 `json:"duration"`
	Width         pgtype.Int4 `json:"width"`
	Height        pgtype.Int4 `json:"height"`
	Status        int16       `json:"status"`
	ReviewNotes   pgtype.Text `json:"review_notes"`
	ReviewedBy    pgtype.Int8 `json:"reviewed_by"`
	ReviewedAt    *time.Time  `json:"reviewed_at"`
	TotalClicks   int64       `json:"total_clicks"`
	ValidClicks   int64       `json:"valid_clicks"`
	LikeCount     int64       `json:"like_count"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	DeletedAt     *time.Time  `json:"deleted_at"`
	AuthorName    string      `json:"author_name"`
	AuthorAvatar  pgtype.Text `json:"author_avatar"`
}

func (q *Queries) ListVideos(ctx context.Context, arg ListVideosParams) ([]ListVideosRow, error) {
	rows, err := q.db.Query(ctx, listVideos, arg.Keyword, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideosRow{}
	for rows.Next() {
		var i ListVideosRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Title,
			&i.Description,
			&i.FileName,
			&i.FileSize,
			&i.FileUrl,
			&i.ThumbnailUrl,
			&i.PreviewGifUrl,
			&i.MimeType,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.Status,
			&i.ReviewNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.TotalClicks,
			&i.ValidClicks,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByCustomer = `-- name: ListVideosByCustomer :many
SELECT v.id, v.customer_id, v.title, v.description, v.file_name, v.file_size, v.file_url, v.thumbnail_url, v.preview_gif_url, v.mime_type, v.duration, v.width, v.height, v.status, v.review_notes, v.reviewed_by, v.reviewed_at, v.total_clicks, v.valid_clicks, v.like_count, v.created_at, v.updated_at, v.deleted_at, c.username AS author_name, c.avatar_url AS author_avatar
FROM videos v
JOIN customers c ON c.id = v.customer_id AND c.deleted_at IS NULL
WHERE v.customer_id = $1 AND v.status = 4 AND v.deleted_at IS NULL
ORDER BY v.created_at DESC
LIMIT $3 OFFSET $2
`

type ListVideosByCustomerParams struct {
	CustomerID int64 `json:"customer_id"`
	OffsetVal  int32 `json:"offset_val"`
	LimitVal   int32 `json:"limit_val"`
}

type ListVideosByCustomerRow struct {
	ID            int64       `json:"id"`
	CustomerID    int64       `json:"customer_id"`
	Title         pgtype.Text `json:"title"`
	Description   pgtype.Text `json:"description"`
	FileName      string      `json:"file_name"`
	FileSize      int64       `json:"file_size"`
	FileUrl       string      `json:"file_url"`
	ThumbnailUrl  pgtype.Text `json:"thumbnail_url"`
	PreviewGifUrl pgtype.Text `json:"preview_gif_url"`
	MimeType      string      `json:"mime_type"`
	Duration      pgtype.Int4 `json:"duration"`
	Width         pgtype.Int4 `json:"width"`
	Height        pgtype.Int4 `json:"height"`
	Status        int16       `json:"status"`
	ReviewNotes   pgtype.Text `json:"review_notes"`
	ReviewedBy    pgtype.Int8 `json:"reviewed_by"`
	ReviewedAt    *time.Time  `json:"reviewed_at"`
	TotalClicks   int64       `json:"total_clicks"`
	ValidClicks   int64       `json:"valid_clicks"`
	LikeCount     int64       `json:"like_count"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	DeletedAt     *time.Time  `json:"deleted_at"`
	AuthorName    string      `json:"author_name"`
	AuthorAvatar  pgtype.Text `json:"author_avatar"`
}

func (q *Queries) ListVideosByCustomer(ctx context.Context, arg ListVideosByCustomerParams) ([]ListVideosByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listVideosByCustomer, arg.CustomerID, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideosByCustomerRow{}
	for rows.Next() {
		var i ListVideosByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Title,
			&i.Description,
			&i.FileName,
			&i.FileSize,
			&i.FileUrl,
			&i.ThumbnailUrl,
			&i.PreviewGifUrl,
			&i.MimeType,
			&i.Duration,
			&i.Width,
			&i.Height,
			&i.Status,
			&i.ReviewNotes,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.TotalClicks,
			&i.ValidClicks,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVideo = `-- name: SoftDeleteVideo :exec
UPDATE videos SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND customer_id = $2 AND deleted_at IS NULL
`

type SoftDeleteVideoParams struct {
	ID         int64 `json:"id"`
	CustomerID int64 `json:"customer_id"`
}

func (q *Queries) SoftDeleteVideo(ctx context.Context, arg SoftDeleteVideoParams) error {
	_, err := q.db.Exec(ctx, softDeleteVideo, arg.ID, arg.CustomerID)
	return err
}
