// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video_play_record.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayRecord = `-- name: CreatePlayRecord :exec
INSERT INTO video_play_records (video_id, customer_id, play_type, ip_address)
VALUES ($1, $2, $3, $4)
`

type CreatePlayRecordParams struct {
	VideoID    int64       `json:"video_id"`
	CustomerID pgtype.Int8 `json:"customer_id"`
	PlayType   int16       `json:"play_type"`
	IpAddress  pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreatePlayRecord(ctx context.Context, arg CreatePlayRecordParams) error {
	_, err := q.db.Exec(ctx, createPlayRecord,
		arg.VideoID,
		arg.CustomerID,
		arg.PlayType,
		arg.IpAddress,
	)
	return err
}
